[package]
name = "task-json"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.140"

[dev-dependencies]
proptest = "1.6.0"
tempdir = "0.3.7"
